title: NeurIPS Workshop Proposal on Gaussian Processes, Spatiotemporal Modeling, and Decision-making Systems
description: A NeurIPS workshop to bring researchers working in Gaussian processes and related areas together
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
future: true
short_title: Gaussian Process Workshop Proposal
header_menu:
    -
        title: "Home"
        link: "/#home"
    -
        title: "Abstract"
        link: "/#abstract"
    -
        title: "Schedule"
        link: "/#schedule"
defaults:
    - scope:
        path: "_posts/current"
      values:
        layout: post
        category: current
    - scope:
        path: "_posts/archive"
      values:
        layout: post
        category: archive
        